<?php
include "header.php";
safe_query("INSERT INTO `consultorios` VALUES (1, 'Domeyko', 1)");
safe_query("INSERT INTO `consultorios` VALUES (2, 'Cerro Navia', 3)");
safe_query("INSERT INTO `consultorios` VALUES (3, 'Albertz', 3)");
safe_query("INSERT INTO `consultorios` VALUES (4, 'Steeger', 3)");
safe_query("INSERT INTO `consultorios` VALUES (5, 'Hernan Urzua', 6)");
safe_query("INSERT INTO `consultorios` VALUES (6, 'Huamachuco', 6)");
safe_query("INSERT INTO `consultorios` VALUES (7, 'Renca', 6)");
safe_query("INSERT INTO `consultorios` VALUES (8, 'Garín', 2)");
safe_query("INSERT INTO `consultorios` VALUES (9, 'Lo Franco', 2)");
safe_query("INSERT INTO `consultorios` VALUES (10, 'Andes', 2)");
safe_query("INSERT INTO `consultorios` VALUES (11, 'Gustavo Molina', 5)");
safe_query("INSERT INTO `consultorios` VALUES (12, 'Pudahuel Poniente', 5)");
safe_query("INSERT INTO `consultorios` VALUES (13, 'Pudahuel Estrella', 5)");
safe_query("INSERT INTO `consultorios` VALUES (14, 'Cardenal Silva Henriquez', 5)");
safe_query("INSERT INTO `consultorios` VALUES (15, 'Santa Anita', 4)");
safe_query("INSERT INTO `consultorios` VALUES (16, 'Yazigi', 4)");
safe_query("INSERT INTO `consultorios` VALUES (17, 'Avendaño', 4)");
safe_query("INSERT INTO `consultorios` VALUES (18, 'Neruda', 4)");
safe_query("INSERT INTO `consultorios` VALUES (19, 'Monckeberg', 8)");
safe_query("INSERT INTO `consultorios` VALUES (20, 'Elgueta', 9)");
safe_query("INSERT INTO `consultorios` VALUES (21, 'San Manuel', 9)");
safe_query("INSERT INTO `consultorios` VALUES (22, 'Boris Soler', 9)");
safe_query("INSERT INTO `consultorios` VALUES (23, 'Adriana madrid', 13)");
safe_query("INSERT INTO `consultorios` VALUES (24, 'Alberto Allende', 7)");
safe_query("INSERT INTO `consultorios` VALUES (25, 'Isla de maipo', 14)");
safe_query("INSERT INTO `consultorios` VALUES (26, 'El Monte', 12)");
safe_query("INSERT INTO `consultorios` VALUES (27, 'Posta Alhué', 15)");
safe_query("INSERT INTO `consultorios` VALUES (28, 'Sta.Rosa de Chena', 11)");
safe_query("INSERT INTO `consultorios` VALUES (29, 'Juan Pablo II', 11)");
safe_query("INSERT INTO `consultorios` VALUES (30, 'Control en otro Consultorio', NULL)");
safe_query("INSERT INTO `consultorios` VALUES (31, 'Control Particular', NULL)");
safe_query("INSERT INTO `consultorios` VALUES (32, 'No se controlaba', NULL)");
safe_query("INSERT INTO `consultorios` VALUES (33, 'Curacaví', 10)");
safe_query("INSERT INTO `consultorios` VALUES (34, 'Melipilla', 9)");
safe_query("INSERT INTO `consultorios` VALUES (35, 'CRS Salvador Allende', 5)");
safe_query("INSERT INTO `consultorios` VALUES (36, 'Penaflor', 8)");
?>
